language: python

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install: python setup.py install

script:
  - wget http://senorpez.servebeer.com/pcars/races/testdata.tar.gz
  - mkdir assets
  - tar -zxvf testdata.tar.gz -C assets/
  - nosetests -v
